name: GitHub Actions Webhook

on:
  push:  # Capture push events on any branch
    branches:
      - '**'  # This will listen to all branches
  pull_request:  # Capture pull request events on any branch
    branches:
      - '**'  # This will listen to all branches

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook event
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"event_type": "${{ github.event_name }}", "branch": "${{ github.ref }}", "author": "${{ github.actor }}"}' \
          http://webhookapp-1.eba-bthgchy3.ap-south-1.elasticbeanstalk.com/webhook
